MONGODB_CONNECTION_STRING = "mongodb+srv://<placeholder>"
JWT_SECRET_KEY = "<placeholder>"
SERVICE_ACCOUNT_JSON_PATH = "./secretstuff/kagame-432309-a28d788b1081.json"
OPENAI_API_KEY = "<placeholder>"
OPENAI_ORG_ID = "<placeholder>"
OPENAI_PROJ_ID = "<placeholder>"